language: php

php:
  - 5.5

services:
  - mysql
  - mongodb
  - rabbitmq
  - redis

before_script:
  - echo "extension=pdo_mysql.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - cp app/config/parameters_test.yml.dist app/config/parameters_test.yml
  - mysql -e 'create database imagepush_test;'
#  - sed s/database_password:/myapp_test/ app/config/parameters.ini-dist | sed s/%database_login%/root/ | sed s/%database_password%// > app/config/parameters.ini
  - composer install --dev

script:
  - phpunit -c app --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

# reduce commit history of git checkout
git:
  depth: 1
