language: php

php:
  - 5.4

services: mongodb

before_script:
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - composer install --dev

script: phpunit -c app
