language: php

php:
  - 5.5

services:
  - mongodb
  - rabbitmq
  - redis

before_script:
  - mongo localhost --eval 'db.addUser("root", "password")'
  - echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install --dev

script: phpunit -c app --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

# reduce commit history of git checkout
git:
  depth: 1
