language: php

php:
  - 7.0

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install --dev

script:
  - phpunit -c app --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

# reduce commit history of git checkout
git:
  depth: 1
