branch-defaults:
  master:
    environment: prod-eb
global:
  application_name: imagepush2
  branch: null
  default_ec2_keyname: anton-server
  default_platform: PHP 5.6
  default_region: eu-west-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
