imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

#parameters:
#  contact_email: anton@antonbabenko.com
  
framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true
        
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    
    # Settings to use in templates
    globals:
      settings:
        show_banners_and_static_helpers: true
        show_comments: true

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
#doctrine:
#    dbal:
#        driver:   %database_driver%
#        host:     %database_host%
#        port:     %database_port%
#        dbname:   %database_name%
#        user:     %database_user%
#        password: %database_password%
#        charset:  UTF8
#
#    orm:
#        auto_generate_proxy_classes: %kernel.debug%
#        auto_mapping: true

doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
    default_database: imagepush_db
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# Redis DB
snc_redis:
    connections:
        default:
            alias: default
            host: 127.0.0.1
            port: 6379
            database: 0
            #password: HeReisTHEMegasuperPuperPassw0rd8595$$@ssssdg7&&.,m!!m
            connection_timeout: 5
            read_write_timeout: 30
            logging: %kernel.debug%
    clients:
        default:
            alias: default
            connection: default
            options:
              profile: 2.2

# Imagine
#liip_imagine:
#    web_root:     %kernel.root_dir%/../web
#    cache_prefix: cache
#    #cache:        true
#    #cache:        custom_cache_resolver
#    #loader:       ~
#    #data_loader:  custom_data_loader
#    driver:       imagick
#    filter_sets:
#      property_main:
#        filters:
#          thumbnail: { size: [620, 400], mode: outbound }
#      company_search:
#        filters:
#          thumbnail: { size: [200, 50], mode: inset }

# Files storage
knp_gaufrette:
    adapters:
        anton_dev:       # My local mac
            local:
                directory:  /Users/Bob/Sites/imagepush2/web/new_uploads
                create:     true
        prod:            # Prod server
            local:
                directory:  /mnt/imagepush/uploads
                create:     true
        prod_s3:         # S3 prod server
            amazon_s3:
                amazon_s3_id: imagepush.amazon.s3
                bucket_name:  uploads.imagepush.to
                create:       true
    filesystems:
        images:
            adapter:    %filesystems_images_adapter%
            #adapter:    prod



services:
    imagepush.images.manager:
        class: Imagepush\ImagepushBundle\Entity\ImagesManager
        arguments: [@router, @snc_redis.default_client, @imagepush.tags.manager]

    imagepush.tags.manager:
        class: Imagepush\ImagepushBundle\Entity\TagsManager
        arguments: [@snc_redis.default_client]

    # Robot services
    imagepush.fetcher.digg:
        class: Imagepush\ImagepushBundle\Services\Fetcher\Digg\DiggFetcher
        arguments: [@kernel]

    imagepush.fetcher.content:
        class: Imagepush\ImagepushBundle\Services\Fetcher\ContentFetcher
        arguments: [@kernel]

    imagepush.processor:
        class: Imagepush\ImagepushBundle\Services\Processor\Processor
        arguments: [@kernel]

    imagepush.processor.tag:
        class: Imagepush\ImagepushBundle\Services\Processor\TagProcessor
        arguments: [@kernel]

    imagepush.publisher:
        class: Imagepush\ImagepushBundle\Services\Publisher\Publisher
        arguments: [@kernel]

    # Amazon S3
    imagepush.amazon.s3:
        class: AmazonS3
        arguments: [%aws_key%, %aws_secret_key%]

    # Twig
    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags:
            - { name: twig.extension }
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }