imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    - { resource: imagepush.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
      engines: ['twig']
      #assets_base_urls:
      #  http: [http://cdn.imagepush.to]
      #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true
        
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    
    # Settings to use in templates
    globals:
      site_url: %site_url%
      cdn_images_url: %cdn_images_url%
      settings:
        show_banners_and_static_helpers: true
        show_comments: true

# Assetic Configuration
assetic:
    #read_from: %kernel.root_dir%/web
    #write_to:  %kernel.root_dir%/web
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine_mongodb:
    connections:
        default:
            server: mongodb://%database_user%:%database_password%@%database_host%:%database_port%
            options:
                connect: true
                persist: true
    proxy_dir:            %kernel.cache_dir%/doctrine/odm/mongodb/Proxies
    hydrator_dir:         %kernel.cache_dir%/doctrine/odm/mongodb/Hydrators
    default_database: imagepush_%kernel.environment%
    document_managers:
        default:
            metadata_cache_driver: apc
            auto_mapping: true
            mappings:
                StofDoctrineExtensionsBundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

stof_doctrine_extensions:
    default_locale: en_US
    mongodb:
        default:
          timestampable: true
          sluggable: true

# Imagine
liip_imagine:
    web_root:     %kernel.root_dir%/../web
    cache_prefix: cache
    #cache:        true
    cache:        custom_cache_resolver
    #loader:       ~
    data_loader:  custom_data_loader
    driver:       imagick
    controller_action: imagepush.imagine.controller:filterAction
    filter_sets:
      out:
        filters:
          thumbnail: { mode: outbound }
      in:
        filters:
          thumbnail: { mode: inset }

# Files storage
knp_gaufrette:
    adapters:
        anton_dev:       # My local mac
            local:
                directory:  /Users/Bob/Sites/imagepush2/web/new_uploads
                create:     true
        prod:         # S3 prod server
            amazon_s3:
                amazon_s3_id: imagepush.amazon.s3
                bucket_name:  %s3_bucket_name%
                create:       true
    filesystems:
        images:
            adapter:    %filesystems_images_adapter%

liip_cache_control:
    rules:
        # the controls section values are used in a call to Response::setCache();
        - { path: ^/test, reverse_proxy_ttl: 30, controls: { public: true, max_age: 10, s_maxage: 20, last_modified: "now" }, vary: [Accept-Encoding, Accept-Language] }
        - { path: ^/, reverse_proxy_ttl: 300, controls: { public: true, max_age: 15, s_maxage: 30 }, vary: [Accept-Encoding, Accept-Language] }
