imports:
    - { resource: config_dev.yml }
    - { resource: parameters_test.yml }

#parameters:
#    doctrine.dbal.connection.wrapper_class: "Imagepush\\DevBundle\\Doctrine\\DBAL\\PersistedConnection"

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
