imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: imagepush.yml }
    - { resource: services.yml }

framework:
    esi:             { enabled: true }
    fragments:       { path: /_fragment }
    translator:      { fallback: en }
    secret:          %secret%
    router:
        strict_requirements: %kernel.debug%
        resource: "%kernel.root_dir%/config/routing.yml"
    default_locale:  en
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
      engines: ['twig']
      #assets_base_urls:
      #  http: [http://cdn.imagepush.to]
      #assets_version: SomeVersionScheme
    session:
        save_path: ~
#    trust_proxy_headers: true
    trusted_proxies: ['127.0.0.1']

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

    # Settings to use in templates
    globals:
      site_url: %site_url%
      cdn_images_url: %cdn_images_url%
      bitly_username: %bitly_username%
      bitly_api_key: %bitly_api_key%
      settings:
        show_banners_and_static_helpers: true
        show_comments: true

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

# Imagine
liip_imagine:
    web_root:     %kernel.root_dir%/../web
    cache_prefix: cache
    cache:        custom_cache_resolver
    data_loader:  custom_data_loader
    driver:       imagick
    controller_action: imagepush.imagine.controller:filterAction
    filter_sets:
      out:
        filters:
          thumbnail: { mode: outbound }
      in:
        filters:
          thumbnail: { mode: inset }

# Files storage
knp_gaufrette:
    adapters:
        anton_dev:       # My local mac
            local:
                directory:  /Users/Bob/Sites/imagepush2/web/new_uploads
                create:     true
        prod:         # S3 prod server
            aws_s3:
                service_id: imagepush.aws.s3
                bucket_name:  %s3_bucket_name%
                options:
                    acl:    public-read
                    create: true
    filesystems:
        images:
            adapter:    %filesystems_images_adapter%

# AWS
aws:
    version: latest
    region: eu-west-1
    credentials: # these should be separate keys during development
        key: "%aws_key%"
        secret: "%aws_secret_key%"
    DynamoDb:
        region: eu-west-1
    S3:
        version: '2006-03-01'
#    Sqs:
#        credentials: "@a_service"
