imports:
    - { resource: config.yml }

#doctrine:
#    metadata_cache_driver: apc
#    result_cache_driver: apc
#    query_cache_driver: apc

#assetic:
#    write_to: s3://i.imagepush.to

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      streamed
            excluded_404s:
                - ^/phpmyadmin
                - ^/wp-
        streamed:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
