# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

front:
    resource: "@ImagepushBundle/Controller/FrontController.php"
    type:     annotation
#
#_imagine:
#    resource: .
#    type:     imagine