front:
    resource: "@ImagepushBundle/Controller/FrontController.php"
    type:     annotation

# Temporary controller to mark best images
#bestImage:
#    resource: "@ImagepushBundle/Controller/BestImageController.php"
#    type:     annotation

#robot:
#    resource: "@ImagepushBundle/Controller/RobotController.php"
#    type:     annotation

#varnish:
#    resource: "@ImagepushBundle/Controller/VarnishController.php"
#    type:     annotation
#
## Small fixes here
#temporary:
#    resource: "@ImagepushBundle/Controller/TemporaryController.php"
#    prefix:   /temp
#    type:     annotation

_imagine:
    resource: .
    type:     imagine
