# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

front:
    resource: "@ImagepushBundle/Controller/FrontController.php"
    type:     annotation

robot:
    resource: "@ImagepushBundle/Controller/RobotController.php"
    prefix:   /robot
    type:     annotation

import:
    resource: "@ImagepushBundle/Controller/ImportController.php"
    prefix:   /import
    type:     annotation
#   
#_imagine:
#    resource: .
#    type:     imagine