services:
    imagepush.images.manager:
        class: Imagepush\ImagepushBundle\Entity\ImagesManager
        arguments: [@router, @snc_redis.default_client, @imagepush.tags.manager]

    imagepush.tags.manager:
        class: Imagepush\ImagepushBundle\Entity\TagsManager
        arguments: [@snc_redis.default_client]

    ##################
    # Robot services #
    ##################
    
    # Fetcher
    imagepush.fetcher.digg:
        class: Imagepush\ImagepushBundle\Services\Fetcher\DiggFetcher
        arguments: [@service_container]

    imagepush.fetcher.content:
        class: Imagepush\ImagepushBundle\Services\Fetcher\ContentFetcher
        arguments: [@service_container]

    # Processor
    imagepush.processor:
        class: Imagepush\ImagepushBundle\Services\Processor\Processor
        arguments: [@service_container, %kernel.debug%]

    imagepush.processor.content:
        class: Imagepush\ImagepushBundle\Services\Processor\Content\Content
        arguments: [@service_container]
        prototype: true

    imagepush.processor.content.html:
        class: Imagepush\ImagepushBundle\Services\Processor\Content\Html
        arguments: [@service_container]
        prototype: true

    # Tag
    imagepush.processor.tag:
        class: Imagepush\ImagepushBundle\Services\Processor\Tag\Tag
        arguments: [@service_container]

    imagepush.processor.tag.source:
        class: Imagepush\ImagepushBundle\Services\Processor\Tag\SourceTag
        arguments: [@service_container]

    imagepush.processor.tag.digg:
        class: Imagepush\ImagepushBundle\Services\Processor\Tag\DiggTag
        arguments: [@service_container]

    imagepush.processor.tag.stumbleupon:
        class: Imagepush\ImagepushBundle\Services\Processor\Tag\StumbleUponTag
        arguments: [@service_container]

    imagepush.processor.tag.twitter:
        class: Imagepush\ImagepushBundle\Services\Processor\Tag\TwitterTag
        arguments: [@service_container]

    imagepush.processor.tag.delicious:
        class: Imagepush\ImagepushBundle\Services\Processor\Tag\DeliciousTag
        arguments: [@service_container]

    imagepush.processor.tag.reddit:
        class: Imagepush\ImagepushBundle\Services\Processor\Tag\RedditTag
        arguments: [@service_container]

    # Publisher
    imagepush.publisher:
        class: Imagepush\ImagepushBundle\Services\Publisher\Publisher
        arguments: [@service_container]


    # Amazon S3
    imagepush.amazon.s3:
        class: Imagepush\ImagepushBundle\Imagine\ImagepushAmazonS3

    #
    imagepush.imagine.controller:
      class: Imagepush\ImagepushBundle\Imagine\CustomController
      arguments: [@liip_imagine.data.manager, @liip_imagine.filter.manager, @liip_imagine.cache.manager, @doctrine.odm.mongodb.document_manager, @liip_imagine, @logger, %kernel.debug%]
      
    # Imagine data loader (via Gaufrette with name "images")
    imagepush.imagine.files.data.loader:
        class: Imagepush\ImagepushBundle\Imagine\CustomDataLoader
        arguments: [@liip_imagine, %liip_imagine.formats%, @gaufrette.images_filesystem]
        tags:
            - { name: liip_imagine.data.loader, loader: custom_data_loader }
 
    # Imagine cache resolver (via Gaufrette with name "images")
    imagepush.imagine.files.cache.resolver:
        class: Imagepush\ImagepushBundle\Imagine\CustomCacheResolver
        arguments: [@service_container, @gaufrette.images_filesystem]
        tags:
            - { name: liip_imagine.cache.resolver, resolver: custom_cache_resolver }

    # Twig
    twig.extension.imagepush:
        class: Imagepush\ImagepushBundle\Templating\ImagepushExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags:
            - { name: twig.extension }
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }