<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ImagepushImagepushBundleDocumentTagHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data)
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = (string) $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['text'])) {
            $value = $data['text'];
            $return = (string) $value;
            $this->class->reflFields['text']->setValue($document, $return);
            $hydratedData['text'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['legacyKey'])) {
            $value = $data['legacyKey'];
            $return = (string) $value;
            $this->class->reflFields['legacyKey']->setValue($document, $return);
            $hydratedData['legacyKey'] = $return;
        }

        /** @Field(type="increment") */
        if (isset($data['usedInAvailable'])) {
            $value = $data['usedInAvailable'];
            $return = $value;
            $this->class->reflFields['usedInAvailable']->setValue($document, $return);
            $hydratedData['usedInAvailable'] = $return;
        }

        /** @Field(type="increment") */
        if (isset($data['usedInUpcoming'])) {
            $value = $data['usedInUpcoming'];
            $return = $value;
            $this->class->reflFields['usedInUpcoming']->setValue($document, $return);
            $hydratedData['usedInUpcoming'] = $return;
        }

        /** @Many */
        $mongoData = isset($data['images']) ? $data['images'] : null;
        $return = new \Doctrine\ODM\MongoDB\PersistentCollection(new \Doctrine\Common\Collections\ArrayCollection(), $this->dm, $this->unitOfWork, '$');
        $return->setOwner($document, $this->class->fieldMappings['images']);
        $return->setInitialized(false);
        if ($mongoData) {
            $return->setMongoData($mongoData);
        }
        $this->class->reflFields['images']->setValue($document, $return);
        $hydratedData['images'] = $return;
        return $hydratedData;
    }
}