<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ImagepushImagepushBundleDocumentLatestTagHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data)
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = (string) $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="timestamp") */
        if (isset($data['timestamp'])) {
            $value = $data['timestamp'];
            $return = $value;
            $this->class->reflFields['timestamp']->setValue($document, $return);
            $hydratedData['timestamp'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['tag'])) {
            $reference = $data['tag'];
            $className = $this->dm->getClassNameFromDiscriminatorValue($this->class->fieldMappings['tag'], $reference);
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($reference['$id']);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['tag']->setValue($document, $return);
            $hydratedData['tag'] = $return;
        }
        return $hydratedData;
    }
}